### ISSUE TITLE
Import policy

### ISSUE THREAD

**Issue by fpetric** [larics/python-pomdp#6]
Write a function for importing policy vectors from a policy pomdpx file.

**Comment by vslosic** [comment]
Is it proper way of solving this issue putting all the values from each vector in matrix that will have dimensions: (number of values inside vector)x(number of vectors)? Also, I could make new policy class that will contain value vectors(or field or matrix) and action vector.

**Comment by fpetric** [comment]
Regarding the first question, it is a design decision you need to make, it seams reasonable to either store it in matrix form or list of vectors. In the first case, you need to extract the row or column to perform the belief update, and I think it is a bit easier to do that if you store policy vectors in a list.
For the second part, lets for now just add all those things to the same class (let it have set of states, actions, observations, transition matrices, observation matrices and policy vectors). For now, it seems to be easier to just cram that into one class and then we can reorganize the code when we start working on  #4

**Comment by vslosic** [comment]
Great, I have also chosen the solution with list of vectors to keep that list format in class. Everything' s clear! :)

**Comment by vslosic** [comment]
Are the actions 0, 1 and 2 equal to drink(0), jump(1) and end(2)? May I import action from attribute also in value vector after the all values defined in tag?

**Comment by fpetric** [comment]
The actions should be in the same order as specified in the original pompx file. Namely, if you have a tag action like this:
`<ActionVar` `vname="action_agent">`
`            <ValueEnum>drink jump end</ValueEnum>`
`</ActionVar>`

then in the policy file action="0" corresponds to the first action in the original tag (drink). 

As for the second question, not sure I understood it correctly.
